# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven-main-build

concurrency: build

on: 
  workflow_call:
#  schedule:
    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 5 15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350
      with:
        egress-policy: audit #outbound hosts constantly subject to change by action providers

    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      with:
        fetch-depth: '0'
        ref: master
    
    - name: Set up JDK 21
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
      with:
        java-version: 21
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@53aa38c736a561b9c17b62df3fe885a17b78ee6d
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache SonarCloud packages
      uses: actions/cache@53aa38c736a561b9c17b62df3fe885a17b78ee6d
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Build and analyze main
      run: |
        export OSM_IMPORT_FILE=https://github.com/datengaertnerei/test-data-service/raw/develop/data/osm-small.pbf
        ./mvnw -B clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        
    - uses: codecov/codecov-action@adfacf2d276b158264c48ff298490fbdf13e4fb6